#!/usr/bin/env php
<?php
/**
 *
 * Gekosale
 *
 * @copyright   Copyright (c) 2012-2013 WellCommerce
 * @author      Adam Piotrowski, apiotrowski@wellcommerce.pl
 */

include 'bootstrap.php';

$console = new Gekosale\Console();
$console->run();