GFormDate.Language = {
	closeText : 'Zamknij',
	prevText : '&#x3c;Poprzedni',
	nextText : 'Następny&#x3e;',
	currentText : 'Dziś',
	monthNames : [ 'Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec',
			'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad',
			'Grudzień' ],
	monthNamesShort : [ 'Sty', 'Lu', 'Mar', 'Kw', 'Maj', 'Cze', 'Lip', 'Sie',
			'Wrz', 'Pa', 'Lis', 'Gru' ],
	dayNames : [ 'Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek',
			'Piątek', 'Sobota' ],
	dayNamesShort : [ 'Nie', 'Pn', 'Wt', 'Śr', 'Czw', 'Pt', 'So' ],
	dayNamesMin : [ 'N', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So' ],
	dateFormat : 'yy-m-d',
	firstDay : 1,
	isRTL : false
};
GException.Language = {
	exception_has_occured : 'Wystąpił błąd!'
};
GForm.Language = {
	select_store : 'Wybierz sklep:',
	add_repetition : 'Dodaj nowy',
	delete_repetition : 'Usuń',
	form_data_invalid : 'Nie można wysłać formularza, ponieważ zawiera on niepoprawne informacje. Przed zapisaniem zmian należy je poprawić.',
	scroll_to_field : 'Przejdź do pola',
	close_alert : 'Zamknij alert',
	next : 'Dalej',
	previous : 'Wstecz',
	save : 'Zapisz',
	add_field_repetition : 'Dodaj nową wartość',
	remove_field_repetition : 'Usuń wartość',
	all_actions : 'wszystkie',
	all_controllers : 'wszystkie',
	product_select_id : 'Id',
	product_select_hierarchy : 'Kolejność',
	product_select_product_id : 'Id produktu',
	product_select_name : 'Nazwa',
	product_select_price : 'Cena netto',
	product_select_price_gross : 'Cena brutto',
	product_select_buyprice : 'Cena zakupu netto',
	product_select_buyprice_gross : 'Cena zakupu brutto',
	product_select_barcode : 'Kod',
	product_select_producer : 'Producent',
	product_select_vat : 'VAT',
	product_select_vat_value : 'Podatek',
	product_select_net_subsum : 'Netto',
	product_select_subsum : 'Brutto',
	product_select_categories : 'Kategoria',
	product_select_adddate : 'Data dodania',
	product_select_adduser : 'Autor',
	product_select_editdate : 'Data modyfikacji',
	product_select_edituser : 'Autor modyfikacji',
	product_select_deselect : 'Anuluj wybór',
	product_select_selected : 'Wybrane produkty',
	product_select_quantity : 'Ilość',
	product_select_variant : 'Wariant produktu',
	product_select_add : 'Dodaj',
	product_select_close_add : 'Ukryj listę produktów',
	product_select_sum : 'Suma',
	datagrid_select_selected : 'Wybrane rekordy',
	datagrid_select_deselect : 'Anuluj wybór',
	datagrid_select_dg_error : 'Błąd podczas inicjalizacji Datagrida',
	file_selector_id : 'Id pliku',
	file_selector_filename : 'Nazwa pliku',
	file_selector_filetype : 'Typ pliku',
	file_selector_extension : 'Rozszerzenie',
	file_selector_deselect : 'Anuluj wybór zdjęcia',
	file_selector_thumb : 'Miniatura',
	file_selector_show_thumb : 'Pokaż miniaturę',
	file_selector_photo : 'Zdjęcie',
	file_selector_photo_main : 'Główne',
	file_selector_photo_visible : 'Widoczne',
	file_selector_photo_cancel : 'Anuluj wybór',
	file_selector_upload_error : 'Błąd podczas wysyłania pliku',
	file_selector_upload_success : 'Wysłano pomyślnie',
	file_selector_processing_error : 'Przetworzanie pliku na serwerze nie powiodło się',
	file_selector_form_blocked : 'Nie wszystkie transfery plików zostały ukończone!',
	file_selector_form_blocked_description : 'Nie można wysłać formularza, dopóki wszystkie transfery nie zostały zakończone. Poczekaj chwilę i spróbuj jeszcze raz.',
	file_selector_selected_image : 'Wybrany plik:',
	product_variants_editor_set_for_this_product : 'Zestaw cech dla tego produktu',
	product_variants_editor_set_for_this_product_suffix : 'sugerowane zestawy są pogrubione',
	product_variants_editor_add_attribute : 'Dodaj nową cechę',
	product_variants_editor_save_attribute : 'Zapisz nową cechę',
	product_variants_editor_add_value : 'Dodaj nową wartość cechy',
	product_variants_editor_save_value : 'Zapisz nową wartość cechy',
	product_variants_editor_id : 'Id wariantu',
	product_variants_editor_stock : 'Magazyn',
	product_variants_editor_modifier_type : 'Typ modyfikatora',
	product_variants_editor_modifier : 'Modyfikator',
	product_variants_editor_price : 'Cena',
	product_variants_editor_add_variant : 'Dodaj nowy wariant',
	product_variants_editor_save_variant : 'Zapisz zmiany',
	product_variants_editor_availble_attributes : 'Cechy dostępne w wybranym zestawie:',
	product_variants_editor_variant_editor_base_net_price : 'Cena podst. netto',
	product_variants_editor_variant_editor_base_gross_price : 'Cena podst. brutto',
	product_variants_editor_variant_editor_modifier_type : 'Rodzaj modyfikatora ceny',
	product_variants_editor_variant_editor_modifier_value : 'Wartość modyfikatora',
	product_variants_editor_variant_editor_net_price : 'Cena netto wariantu',
	product_variants_editor_variant_editor_gross_price : 'Cena brutto wariantu',
	product_variants_editor_variant_editor_stock : 'Stan magazynowy',
	product_variants_editor_choose_attribute : '(wybierz cechę)',
	tree_add_item : 'Dodaj',
	tree_duplicate_item : 'Duplikuj',
	tree_add_subitem : 'Nowa podrzędna',
	tree_delete_item : 'Usuń zaznaczoną',
	tree_save_order : 'Zapisz kolejność',
	tree_restore_order : 'Przywróć kolejność',
	tree_expand_all : 'Rozwiń wszystkie',
	tree_retract_all : 'Zwiń wszystkie',
	tree_ok : 'OK',
	tree_cancel : 'Anuluj',
	tree_found_duplicates : 'Znaleziono dwa elementy o tej samej nazwie na jednym poziomie',
	tree_duplicate_entry_all_levels : 'Znaleziono dwa elementy o tej samej nazwie',
	tree_found_duplicates_description : 'Proponowanej struktury nie można zapisać, ponieważ zawiera zduplikowane elementy na tym samym poziomie w tym samym poddrzewie.',
	tree_duplicate_entry_all_levels_description : 'Proponowanej struktury nie można zapisać, ponieważ zawiera zduplikowane elementy.',
	tree_duplicate_entry : 'Element o tej nazwie już istnieje',
	tree_duplicate_entry_description : 'Na jednym poziomie poddrzewa nie mogą się znaleźć dwa elementy o tej samej nazwie.',
	tree_delete_item_warning : 'Czy na pewno chcesz usunąć tę kategorię?',
	tree_delete_item_warning_description : 'Usunięcie będzie nieodwracalne. Przed usunięciem kategorii należy upewnić się, że nie zawiera ona podkategorii.',
	tree_deselect : 'Anuluj wybór',
	attribute_editor_choose_attribute : '(wybierz lub wpisz cechę)',
	technical_attribute_editor_choose_attribute : '(wybierz grupę lub wpisz nazwę nowej)',
	attribute_editor_rename_attribute : 'Zmień nazwę cechy',
	attribute_editor_rename_attribute_provide_new_name : 'Podaj nową nazwę (pamiętaj, że zmieni się ona we wszystkich grupach i produktach!):',
	attribute_editor_rename_attribute_error : 'Zmiana nazwy cechy nie powiodła się',
	attribute_editor_rename_attribute_error_description : 'Wystąpił błąd podczas dokonywania zmiany w bazie danych.',
	attribute_editor_rename_value : 'Zmień nazwę wartości cechy',
	attribute_editor_rename_value_provide_new_name : 'Podaj nową nazwę (pamiętaj, że zmieni się ona we wszystkich grupach i produktach!):',
	attribute_editor_rename_value_error : 'Zmiana nazwy wartości cechy nie powiodła się',
	attribute_editor_rename_value_error_description : 'Wystąpił błąd podczas dokonywania zmiany w bazie danych.',
	attribute_editor_remove_attribute : 'Usuń z grupy',
	attribute_editor_remove_attribute_from_base : 'Usuń z bazy danych',
	attribute_editor_remove_attribute_from_base_ok : 'Usuń',
	attribute_editor_remove_attribute_from_base_cancel : 'Anuluj',
	attribute_editor_remove_attribute_from_base_confirm : 'Czy na pewno chcesz usunąć tę cechę z bazy danych?',
	attribute_editor_remove_attribute_from_base_confirm_description : 'Spowoduje to utratę wszystkich należących do tej cechy wartości. Ponowne użycie tej cechy będzie wymagało jej dodania do bazy.',
	attribute_editor_remove_attribute_from_base_error : 'Usunięcie cechy z bazy nie powiodło się.',
	attribute_editor_remove_attribute_from_base_error_description : 'Sprawdź, czy usuwana cecha nie jest przypisana któremuś z produktów bądź nie przynależy do innego zestawu cech.',
	attribute_editor_edit_attribute_values : 'Edytuj wartości cechy',
	attribute_editor_remove_value : 'Usuń wartość cechy',
	attribute_editor_add_attribute : 'Dodaj cechę',
	attribute_editor_add_value : 'Dodaj wartość cechy',
	attribute_editor_attributes : 'Cechy',
	technical_attribute_editor_attributes : 'Grupa atrybutów',
	attribute_editor_values : 'Wartości',
	technical_attribute_editor_values : 'Atrybuty',
	client_select_id : 'Id',
	client_select_first_name : 'Imię',
	client_select_surname : 'Nazwisko',
	client_select_email : 'E-mail',
	client_select_phone : 'Telefon',
	client_select_sex : 'Płeć',
	client_select_group : 'Grupa',
	client_select_adddate : 'Data utworzenia konta',
	client_select_editdate : 'Data modyfikacji',
	client_select_add_client : 'Dodaj klienta',
	client_select_select_client : 'Wybierz klienta',
	product_select_close_selection : 'Ukryj listę klientów',
	client_select_client_name : 'Dane osobowe',
	client_select_client_email : 'Adres e-mail',
	client_select_client_group : 'Przynależy do grupy',
	address_different : '(inny adres)',
	address_copy_from : 'Skopiuj adres z:',
	address_update_data : 'Czy zaktualizować dane adresowe?',
	address_update_data_description : 'Zmieniono klienta dla zamówienia. Czy automatycznie ustawić dane płatnika i dane wysyłki na podstawie danych adresowych klienta?',
	product_aggregator_form_blocked : 'Trwa przeliczanie ceny zestawu!',
	product_aggregator_form_blocked_description : 'Nie można zapisać zmian, dopóki przeliczanie nie zostanie ukończone.',
	product_aggregator_count : 'Liczba produktów',
	product_aggregator_sum : 'Suma',
	product_aggregator_setvalue_prohibited : 'Wywołanie metody SetValue dla pola typu FE_ProductAggregator jest niedozwolone.',
	price_modifier_value : 'Wartość modyfikatora',
	price_modifier_modifier : 'Rodzaj modyfikatora',
	range_editor_use_vat : 'Uwzględnij podatek VAT',
	range_editor_vat : 'Stawka VAT',
	range_editor_from : 'od',
	range_editor_to : 'do',
	range_editor_add_range : 'Dodaj nowy zakres poniżej tego',
	range_editor_remove_range : 'Usuń zakres',
	datetime_hour : 'godzina',
	static_listing_collapse : 'Zwiń',
	static_listing_expand : 'Rozwiń',
	preview_trigger_label : '(Podgląd)',
	colour_scheme_picker_colour : 'Kolor',
	colour_scheme_picker_gradient : 'Gradient',
	colour_scheme_picker_image : 'Grafika',
	colour_scheme_picker_background_position : 'Wyrównanie tła',
	colour_scheme_picker_background_repeat : 'Powtarzanie tła',
	colour_scheme_picker_background_repeat_no : 'bez powtarzania',
	colour_scheme_picker_background_repeat_x : 'w poziomie',
	colour_scheme_picker_background_repeat_y : 'w pionie',
	colour_scheme_picker_background_repeat_xy : 'w poziomie i w pionie',
	localfile_select : 'Wybierz z biblioteki',
	localfile_unselect : 'Zamknij bibliotekę',
	localfiles_select : 'Wybierz z biblioteki',
	localfile_processing_error : 'Wysłanie pliku nie powiodło się',
	localfile_none_selected : '(nie wybrano pliku)',
	localfile_fullpath : 'Pełna ścieżka',
	localfile_filename : 'Nazwa pliku',
	localfile_filesize : 'Rozmiar pliku',
	localfile_fileowner : 'Właściciel',
	localfile_filemtime : 'Ost. modyfikacja',
	localfile_delete : 'Usuń plik',
	localfile_delete_warning : 'Czy na pewno chcesz usunąć ten plik?',
	localfile_delete_warning_description : 'Jeśli jest on używany w innym miejscu, jego usunięcie może doprowadzić do niepoprawnego wyświetlania sklepu u klientów.',
	localfile_ok : 'OK',
	localfile_cancel : 'Anuluj',
	border_none : 'brak',
	border_side_top : 'Górne obramowanie',
	border_side_right : 'Prawe obramowanie',
	border_side_bottom : 'Dolne obramowanie',
	border_side_left : 'Lewe obramowanie',
	border_separate : 'Rozdziel strony obramowania',
	layout_boxes_list_span : 'Rozciągnij:',
	layout_boxes_list_collapsed : 'Zwinięty',
	layout_boxes_list_add : 'Dodaj boks',
	layout_boxes_list_remove : 'Usuń boks',
	technical_data_choose_set : 'Zestaw atrybutów',
	technical_data_save_set : 'Zapisz jako wybrany zestaw',
	technical_data_save_as_new_set : 'Zapisz zestaw pod nową nazwą',
	technical_data_delete_set : 'Usuń wybrany zestaw',
	technical_data_unsaved_changes : 'Zmiana zestawu',
	technical_data_unsaved_changes_description : 'Wprowadziłeś zmiany, które nie zostaną zapisane. Czy chcesz kontynuować?',
	technical_data_unsaved_changes_save : 'Zapisz',
	technical_data_unsaved_changes_discard : 'Tak, zmień zestaw',
	technical_data_unsaved_changes_cancel : 'Anuluj zmianę zestawu',
	technical_data_save_set_success : 'Zapisano zestaw',
	technical_data_save_set_success_description : 'Zapisanie zestawu powiodło się.',
	technical_data_add_new_set : 'Podaj nazwę nowego zestawu atrybutów',
	technical_data_delete_set_description : 'Po usunięciu zestawu, ten produkt nadal będzie posiadał obecnie wybrane dane techniczne, jednak nie będzie możliwe przypisanie ich zestawu innemu produktowi dopóki nie zostanie utworzony nowy zestaw. Czy na pewno chcesz usunąć ten zestaw?',
	technical_data_delete_set_success : 'Usunięto zestaw',
	technical_data_delete_set_success_description : 'Usunięcie zestawu powiodło się.',
	technical_data_add_new_group : 'Dodaj nową grupę danych',
	technical_data_delete_group : 'Usuń tę grupę danych',
	technical_data_save_group : 'Zapisz',
	technical_data_delete_group_permanently : 'Usuń',
	technical_data_save_group_success : 'Zapisano zmiany w grupie',
	technical_data_save_group_success_description : 'Zapisanie zmian w grupie danych powiodło się.',
	technical_data_delete_attribute_group : 'Usuń wybraną grupę danych technicznych',
	technical_data_delete_attribute_group_description : 'Trwałe usunięcie spowoduje zniknięcie tej grupy także w przypadku innych produktów. Czy chcesz kontynuować?',
	technical_data_delete_group_success : 'Usunięto grupę danych',
	technical_data_delete_group_success_description : 'Usunięcie grupy danych powiodło się.',
	technical_data_save_attribute : 'Zapisz',
	technical_data_delete_attribute_permanently : 'Usuń',
	technical_data_delete_attribute : 'Usuń wybrany atrybut',
	technical_data_delete_attribute_description : 'Trwałe usunięcie spowoduje zniknięcie tego atrybutu także w przypadku innych produktów. Czy chcesz kontynuować?',
	technical_data_delete_attribute_success : 'Usunięto atrybut',
	technical_data_delete_attribute_success_description : 'Usunięcie atrybutu powiodło się.',
	technical_data_save_attribute_success : 'Zapisano zmiany w atrybucie',
	technical_data_save_attribute_success_description : 'Zapisanie zmian w atrybucie powiodło się.',
	technical_data_edit_attribute : 'Edytuj wybrany atrybut',
	technical_data_edit_group : 'Edytuj wybraną grupę',
	technical_data_add_new_attribute : 'Dodaj nowy atrybut do tej grupy',
	technical_data_edit_multilingual_value : 'Edytuj tę wartość w innych językach',
	technical_data_value_type_string : 'Tekst / Liczba',
	technical_data_value_type_multilingual_string : 'Wartość wielojęzyczna',
	technical_data_value_type_text : 'Tekst',
	technical_data_value_type_image : 'Obraz',
	technical_data_value_type_boolean : 'Tak/Nie',
	technical_data_value_type_select : 'Lista wyboru',
	technical_data_value_type_multiselect : 'Lista wielokrotnego wyboru',
	progress_indicator_run_comment : 'Kliknij przycisk Uruchom',
	progress_indicator_run : 'Uruchom',
	progress_indicator_success : 'Operacja zakończona powodzeniem',
	help : 'Pomoc',
	order_editor_historical_product : 'Produkt został usunięty z bazy!',
	allegro_product_select_description: 'Opis',
	allegro_product_select_category: 'Kategoria Allegro',
	allegro_product_select_params: 'Parametry Allegro',
	allegro_product_select_shop_net_buyprice: 'Cena netto zakupu',
	allegro_product_select_shop_gross_buyprice: 'Cena brutto zakupu',
	allegro_product_select_shop_net_price: 'Cena netto',
	allegro_product_select_shop_gross_price: 'Cena brutto',
	allegro_product_select_start_price: 'Wywoławcza',
	allegro_product_select_buy_price: 'Kup Teraz',
	allegro_product_select_min_price: 'Minimalna',
	allegro_product_select_title: 'Tytuł aukcji',
	allegro_product_select_product_id: 'Id produktu',
	allegro_product_select_products_list: 'Wybierz produkty',
	allegro_product_select_title_format: 'Format tytułu aukcji',
	allegro_product_select_selected_products: 'Produkty do wystawienia',
	allegro_product_select_autotitle: 'Zastosuj automatyczne generowanie tytułów aukcji',
	allegro_product_select_edit_description: 'Edytuj opis aukcji',
	allegro_product_select_product_description: 'Opis wybranego produktu',
	allegro_product_select_save_description: 'Zapisz opis',
	allegro_product_select_favourite_categories: 'Kategorie ulubione',
	allegro_product_select_related_categories: 'Kategorie powiązane',
	allegro_product_select_all_categories: 'Wszystkie kategorie',
	allegro_product_select_params: 'Parametry Allegro'

};
GMenu.Language = {
	customize : 'Dostosuj menu',
	choose_mode : 'Kiedy podmenu ma zostać rozwinięte?',
	mode_click : 'Po kliknięciu',
	mode_hover : 'Po najechaniu kursorem',
	mode_delay : 'Po najechaniu kursorem i opóźnieniu',
	mode_delay_ms : 'ms',
	save : 'Zapisz',
	save_desc : 'Zapamiętaj ustawienia dotyczące menu',
	restore_default : 'Przywróć domyślne',
	restore_default_desc : 'Przywróć domyślne ustawienia dotyczące menu'
};

GMessageBar.Language = {
	close_alert : 'OK',
	cancel : 'Anuluj',
	ok : 'OK',
	add : 'OK',
	yes : 'Tak',
	no : 'Nie'
};
GScrollableTabs.Language = {
	next : 'Przewiń w prawo',
	previous : 'Przewiń w lewo'
};


GF_Datagrid.Language = {
	options: '<span class="hidden">Opcje</span>',
	select_all: 'Zaznacz wszystkie',
	modify_columns: 'Zmień ustawienia kolumn',
	retract_filters: 'Zwiń filtry',
	expand_filters: 'Rozwiń filtry',
	from: 'From',
	to: 'To',
	delete_group: 'Usuń wybrane rekordy',
	delete_row: 'Delete',
	edit_row: 'Edit',
	view_row: 'Wyświetl rekord',
	records_shown: 'Records:',
	out_of: 'of',
	choose_page: 'Page:',
	go_to_prev_page: 'Przejdź do poprzedniej strony',
	go_to_next_page: 'Przejdź do następnej strony',
	go_to_first_page: 'Przejdź do pierwszej strony',
	go_to_last_page: 'Przejdź do ostatniej strony',
	selected_records: 'Wybranych:',
	clear_selection: 'Anuluj wybór',
	confirm: 'OK',
	restore_default: 'Restore defaults',
	restore_default_desc: 'Przywróć domyślne ustawienia kolumn dla tego modułu',
	save_and_confirm: 'Save settings',
	save_and_confirm_desc: 'Zapamiętaj ustawienia i szerokości kolumn, aby stały się domyślnymi dla tego modułu',
	no_rows_selected: 'Nie wybrano żadnego wiersza.',
	not_all_shown: 'Uwaga! Zastosowano filtrację. Ukrytych rekordów: ',
	filter_tree_expand: 'Choose',
	filter_tree_retract: 'Collapse',
	filter_tree_cancel: 'Remove from filter',
	filter_tree_cancel_all: 'Reset',
	filter_tree_empty: '(brak filtracji)'
};
